# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
################################################################################
#
#   Profile
#
#   - Different configuration profiles may be encoded here to be specified
#   as parameters to the configtxgen tool
#
################################################################################
Profiles:

    ThreeOrgOrdererGenesis:
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *OrdererOrg
        Consortiums:
            PublicConsortium:
                Organizations:
                    - *PubHos1
                    - *PubHos2
            PrivateConsortium:
                Organizations:
                    - *PriHos1
            CommonConsortium:
                Organizations:
                    - *PubHos1
                    - *PubHos2
                    - *PriHos1

    PublicOrgChannel:
        Consortium: PublicConsortium
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *PubHos1
                - *PubHos2

    PrivateOrgChannel:
        Consortium: PrivateConsortium
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *PriHos1

    CommonOrgChannel:
        Consortium: CommonConsortium
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *PubHos1
                - *PubHos2
                - *PriHos1

################################################################################
#
#   Section: Organizations
#
#   - This section defines the different organizational identities which will
#   be referenced later in the configuration.
#
################################################################################
Organizations:

    # SampleOrg defines an MSP using the sampleconfig.  It should never be used
    # in production but may be used as a template for other definitions
    - &OrdererOrg
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: OrdererOrg

        # ID to load the MSP definition as
        ID: OrdererMSP

        # MSPDir is the filesystem path which contains the MSP configuration
        MSPDir: crypto-config/ordererOrganizations/example.com/msp

    - &PubHos1
        Name: PubHos1MSP

        ID: PubHos1MSP

        MSPDir: crypto-config/peerOrganizations/pubhos1.example.com/msp

        AnchorPeers:
            - Host: icu.pubhos1.example.com
              Port: 7051

    - &PubHos2
        Name: PubHos2MSP

        ID: PubHos2MSP

        MSPDir: crypto-config/peerOrganizations/pubhos2.example.com/msp

        AnchorPeers:
            - Host: icu.pubhos2.example.com
              Port: 7051

    - &PriHos1
        Name: PriHos1MSP

        ID: PriHos1MSP

        MSPDir: crypto-config/peerOrganizations/prihos1.example.com/msp

        AnchorPeers:
            - Host: icu.prihos1.example.com
              Port: 7051

################################################################################
#
#   SECTION: Orderer
#
#   - This section defines the values to encode into a config transaction or
#   genesis block for orderer related parameters
#
################################################################################
Orderer: &OrdererDefaults

    # Orderer Type: The orderer implementation to start
    # Available types are "solo" and "kafka"
    OrdererType: solo

    Addresses:
        - orderer.example.com:7050

    # Batch Timeout: The amount of time to wait before creating a batch
    BatchTimeout: 2s

    # Batch Size: Controls the number of messages batched into a block
    BatchSize:

        # Max Message Count: The maximum number of messages to permit in a batch
        MaxMessageCount: 10

        # Absolute Max Bytes: The absolute maximum number of bytes allowed for
        # the serialized messages in a batch.
        AbsoluteMaxBytes: 99 MB

        # Preferred Max Bytes: The preferred maximum number of bytes allowed for
        # the serialized messages in a batch. A message larger than the preferred
        # max bytes will result in a batch larger than preferred max bytes.
        PreferredMaxBytes: 512 KB

    Kafka:
        # Brokers: A list of Kafka brokers to which the orderer connects
        # NOTE: Use IP:port notation
        Brokers:
            - 127.0.0.1:9092

    # Organizations is the list of orgs which are defined as participants on
    # the orderer side of the network
    Organizations:

################################################################################
#
#   SECTION: Application
#
#   - This section defines the values to encode into a config transaction or
#   genesis block for application related parameters
#
################################################################################
Application: &ApplicationDefaults

    # Organizations is the list of orgs which are defined as participants on
    # the application side of the network
    Organizations:
