# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# ---------------------------------------------------------------------------
# "OrdererOrgs" - Definition of organizations managing orderer nodes
# -----------------------------------------------------------------------------
OrdererOrgs:
  # ---------------------------------------------------------------------------
  # Orderer
  # ---------------------------------------------------------------------------
  - Name: Orderer
    Domain: example.com
    # --------------------------------------------------------------------------
    # "Specs" - See PeerOrgs below for complete description
    # --------------------------------------------------------------------------
    Specs:
      - Hostname: orderer
# ---------------------------------------------------------------------------
# "PeerOrgs" - Definition of organizations managing peer nodes
# ---------------------------------------------------------------------------
PeerOrgs:
  # ---------------------------------------------------------------------------
  # PubHos1
  # ---------------------------------------------------------------------------
  - Name: PubHos1
    Domain: pubhos1.example.com
    # --------------------------------------------------------------------------
    # "Specs"
    # --------------------------------------------------------------------------
    Specs:
      - Hostname: icu
      - Hostname: surgery
      - Hostname: ir
    # --------------------------------------------------------------------------
    # "Users"
    Users:
      Count: 3
  # ---------------------------------------------------------------------------
  # PubHos2
  # ---------------------------------------------------------------------------
  - Name: PubHos2
    Domain: pubhos2.example.com
    # --------------------------------------------------------------------------
    # "Specs"
    # --------------------------------------------------------------------------
    Specs:
      - Hostname: icu
      - Hostname: surgery
      - Hostname: ir
    # --------------------------------------------------------------------------
    # "Users"
    Users:
      Count: 3
  # ---------------------------------------------------------------------------
  # PriHos1
  # ---------------------------------------------------------------------------
  - Name: PriHos1
    Domain: prihos1.example.com
    # --------------------------------------------------------------------------
    # "Specs"
    # --------------------------------------------------------------------------
    Specs:
      - Hostname: icu
      - Hostname: surgery
      - Hostname: ir
    # --------------------------------------------------------------------------
    # "Users"
    Users:
      Count: 3
