#
# Copyright IBM Corp All Rights Reserved
#
# SPDX-License-Identifier: Apache-2.0
#
version: '2'

networks:
  basic:

services:
  ca.example.com:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.example.com
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.ha.example.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/7128c86348bc24f1de112453188993a6a098dec9f5db031942e8a03f2b9ad514_sk
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/ha.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.example.com
    networks:
      - basic

  orderer.example.com:
    container_name: orderer.example.com
    extends:
      file: base/docker-compose-base.yml
      service: orderer-base.example.com
    ports:
      - 7050:7050
    volumes:
      - ./crypto-config/peerOrganizations/ha.example.com/peers/ce.ha.example.com/:/etc/hyperledger/ha
      - ./crypto-config/peerOrganizations/ha.example.com/peers/ce.pubhos1.example.com/:/etc/hyperledger/pubhos1
      - ./crypto-config/peerOrganizations/ha.example.com/peers/surgery.pubhos1.example.com/:/etc/hyperledger/pubhos1
      - ./crypto-config/peerOrganizations/ha.example.com/peers/ir.pubhos1.example.com/:/etc/hyperledger/pubhos1
      - ./crypto-config/peerOrganizations/ha.example.com/peers/ce.prihos1.example.com/:/etc/hyperledger/prihos1
      - ./crypto-config/peerOrganizations/ha.example.com/peers/surgery.prihos1.example.com/:/etc/hyperledger/prihos1
      - ./crypto-config/peerOrganizations/ha.example.com/peers/ir.prihos1.example.com/:/etc/hyperledger/prihos1
    working_dir: /etc/hyperledger/configtx/
    networks:
      - basic

  ce.ha.example.com:
    container_name: ce.ha.example.com
    extends:
      file: base/docker-compose-base.yml
      service: peer-base.ha.example.com
    environment:
      - CORE_PEER_ID=ce.ha.example.com
      - CORE_PEER_ADDRESS=ce.ha.example.com:7051
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0:5984
    ports:
      - 7051:7051
      - 7053:7053
    volumes:
      - ./crypto-config/peerOrganizations/ha.example.com/peers/ce.ha.example.com/:/etc/hyperledger/peer/
    working_dir: /etc/hyperledger/configtx/
    depends_on:
      - orderer.example.com
      - couchdb0
    networks:
      - basic


  ce.pubhos1.example.com:
    container_name: ce.pubhos1.example.com
    extends:
      file: base/docker-compose-base.yml
      service: peer-base.pubhos1.example.com
    environment:
      - CORE_PEER_ID=ce.pubhos1.example.com
      - CORE_PEER_ADDRESS=ce.pubhos1.example.com:7051
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1:5984
    ports:
      - 8051:7051
      - 8053:7053
    volumes:
      - ./crypto-config/peerOrganizations/pubhos1.example.com/peers/ce.pubhos1.example.com/:/etc/hyperledger/peer/
    working_dir: /etc/hyperledger/configtx/
    depends_on:
      - orderer.example.com
      - couchdb1
    networks:
      - basic

  surgery.pubhos1.example.com:
    container_name: surgery.pubhos1.example.com
    extends:
      file: base/docker-compose-base.yml
      service: peer-base.pubhos1.example.com
    environment:
      - CORE_PEER_ID=surgery.pubhos1.example.com
      - CORE_PEER_ADDRESS=surgery.pubhos1.example.com:7051
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb2:5984
    ports:
      - 8151:7051
      - 8153:7053
    volumes:
      - ./crypto-config/peerOrganizations/pubhos1.example.com/peers/surgery.pubhos1.example.com/:/etc/hyperledger/peer/
    working_dir: /etc/hyperledger/configtx/
    depends_on:
      - orderer.example.com
      - couchdb2
      - ce.pubhos1.example.com
    networks:
      - basic

  ir.pubhos1.example.com:
    container_name: ir.pubhos1.example.com
    extends:
      file: base/docker-compose-base.yml
      service: peer-base.pubhos1.example.com
    environment:
      - CORE_PEER_ID=ir.pubhos1.example.com
      - CORE_PEER_ADDRESS=ir.pubhos1.example.com:7051
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb3:5984
    ports:
      - 8251:7051
      - 8253:7053
    volumes:
      - ./crypto-config/peerOrganizations/pubhos1.example.com/peers/ir.pubhos1.example.com/:/etc/hyperledger/peer/
    working_dir: /etc/hyperledger/configtx/
    depends_on:
      - orderer.example.com
      - couchdb3
      - ce.pubhos1.example.com
    networks:
      - basic

  ce.prihos1.example.com:
    container_name: ce.prihos1.example.com
    extends:
      file: base/docker-compose-base.yml
      service: peer-base.prihos1.example.com
    environment:
      - CORE_PEER_ID=ce.prihos1.example.com
      - CORE_PEER_ADDRESS=ce.prihos1.example.com:7051
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb4:5984
    ports:
      - 9051:7051
      - 9053:7053
    volumes:
      - ./crypto-config/peerOrganizations/prihos1.example.com/peers/ce.prihos1.example.com/:/etc/hyperledger/peer/
    working_dir: /etc/hyperledger/configtx/
    depends_on:
      - orderer.example.com
      - couchdb4
    networks:
      - basic

  surgery.prihos1.example.com:
    container_name: surgery.prihos1.example.com
    extends:
      file: base/docker-compose-base.yml
      service: peer-base.prihos1.example.com
    environment:
      - CORE_PEER_ID=surgery.prihos1.example.com
      - CORE_PEER_ADDRESS=surgery.prihos1.example.com:7051
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb5:5984
    ports:
      - 9151:7051
      - 9153:7053
    volumes:
      - ./crypto-config/peerOrganizations/prihos1.example.com/peers/surgery.prihos1.example.com/:/etc/hyperledger/peer/
    working_dir: /etc/hyperledger/configtx/
    depends_on:
      - orderer.example.com
      - couchdb5
      - ce.prihos1.example.com
    networks:
      - basic

  ir.prihos1.example.com:
    container_name: ir.prihos1.example.com
    extends:
      file: base/docker-compose-base.yml
      service: peer-base.prihos1.example.com
    environment:
      - CORE_PEER_ID=ir.prihos1.example.com
      - CORE_PEER_ADDRESS=ir.prihos1.example.com:7051
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb6:5984
    ports:
      - 9251:7051
      - 9253:7053
    volumes:
      - ./crypto-config/peerOrganizations/prihos1.example.com/peers/ir.prihos1.example.com/:/etc/hyperledger/peer/
    working_dir: /etc/hyperledger/configtx/
    depends_on:
      - orderer.example.com
      - couchdb6
      - ce.prihos1.example.com
    networks:
      - basic

  couchdb0:
    container_name: couchdb0
    extends:
      file: base/docker-compose-base.yml
      service: couchdb-base
    ports:
      - 5984:5984
    networks:
      - basic

  couchdb1:
    container_name: couchdb1
    extends:
      file: base/docker-compose-base.yml
      service: couchdb-base
    ports:
      - 6084:5984
    networks:
      - basic

  couchdb2:
    container_name: couchdb2
    extends:
      file: base/docker-compose-base.yml
      service: couchdb-base
    ports:
      - 6184:5984
    networks:
      - basic

  couchdb3:
    container_name: couchdb3
    extends:
      file: base/docker-compose-base.yml
      service: couchdb-base
    ports:
      - 6284:5984
    networks:
      - basic

  couchdb4:
    container_name: couchdb4
    extends:
      file: base/docker-compose-base.yml
      service: couchdb-base
    ports:
      - 6384:5984
    networks:
      - basic

  couchdb5:
    container_name: couchdb5
    extends:
      file: base/docker-compose-base.yml
      service: couchdb-base
    ports:
      - 6484:5984
    networks:
      - basic

  couchdb6:
    container_name: couchdb6
    extends:
      file: base/docker-compose-base.yml
      service: couchdb-base
    ports:
      - 6584:5984
    networks:
      - basic

  cli:
    container_name: cli
    image: hyperledger/fabric-tools
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=ce.pubhos1.example.com:7051
      - CORE_PEER_LOCALMSPID=PubHos1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/peer/crypto/peerOrganizations/pubhos1.example.com/users/Admin@pubhos1.example.com/msp
      - CORE_CHAINCODE_KEEPALIVE=10
      ########## TLS ##########
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/peer/crypto/peerOrganizations/pubhos1.example.com/peers/ce.pubhos1.example.com/tls/ca.crt
    working_dir: /opt/gopath/src/ #/opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
      - /var/run/:/host/var/run/
      - ./../chaincode/:/opt/gopath/src/github.com/
      - ./crypto-config:/etc/hyperledger/fabric/peer/crypto/
      - ./volumes/client/:/opt/gopath/src/myprj/
    networks:
      - basic

  cli2:
    container_name: cli2
    image: hyperledger/fabric-tools
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=cli2
      - CORE_PEER_ADDRESS=ce.prihos1.example.com:7051
      - CORE_PEER_LOCALMSPID=PriHos1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/peer/crypto/peerOrganizations/prihos1.example.com/users/Admin@prihos1.example.com/msp
      - CORE_CHAINCODE_KEEPALIVE=10
      ########## TLS ##########
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/peer/crypto/peerOrganizations/prihos1.example.com/peers/ce.prihos1.example.com/tls/ca.crt
    working_dir: /opt/gopath/src/ #/opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
      - /var/run/:/host/var/run/
      - ./../chaincode/:/opt/gopath/src/github.com/
      - ./crypto-config:/etc/hyperledger/fabric/peer/crypto/
      - ./volumes/client/:/opt/gopath/src/myprj/
    networks:
      - basic
