#
# Copyright IBM Corp All Rights Reserved
#
# SPDX-License-Identifier: Apache-2.0
#
version: '2'

networks:
  basic:

services:
  orderer-base.example.com:
    image: hyperledger/fabric-orderer
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/orderer/msp
      ########## TLS ##########
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/etc/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/etc/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/etc/hyperledger/orderer/tls/ca.crt]
    working_dir: /etc/hyperledger/configtx
    command: orderer
    volumes:
      - ../config/:/etc/hyperledger/configtx
      - ../crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/:/etc/hyperledger/orderer
    networks:
      - basic

  peer-base.ha.example.com:
    extends:
      file: peer-base.yml
      service: peer-base
    environment:
      - CORE_PEER_LOCALMSPID=HAMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/users/Admin@ha.example.com/msp
    volumes:
      - ../crypto-config/peerOrganizations/ha.example.com/users:/etc/hyperledger/users/
    networks:
      - basic

  peer-base.pubhos1.example.com:
    extends:
      file: peer-base.yml
      service: peer-base
    environment:
      - CORE_PEER_LOCALMSPID=PubHos1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/users/Admin@pubhos1.example.com/msp
    volumes:
      - ../crypto-config/peerOrganizations/pubhos1.example.com/users:/etc/hyperledger/users/
    networks:
      - basic

  peer-base.prihos1.example.com:
    extends:
      file: peer-base.yml
      service: peer-base
    environment:
      - CORE_PEER_LOCALMSPID=PriHos1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/users/Admin@prihos1.example.com/msp
    volumes:
      - ../crypto-config/peerOrganizations/prihos1.example.com/users:/etc/hyperledger/users/
    networks:
      - basic

  couchdb-base:
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    networks:
      - basic
